// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkud8b0rg7qMaGTUurfpBFebC4vbY9J6c',
    appId: '1:623939344647:web:a2ac8f420641c32cabcda2',
    messagingSenderId: '623939344647',
    projectId: 'whatsapp-group-link-bef0d',
    authDomain: 'whatsapp-group-link-bef0d.firebaseapp.com',
    storageBucket: 'whatsapp-group-link-bef0d.appspot.com',
    measurementId: 'G-1BRQX2L99H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpN4jXJF_ktNVyMV_goqUi83GmilAtdYE',
    appId: '1:623939344647:android:dc50c2f036ce6492abcda2',
    messagingSenderId: '623939344647',
    projectId: 'whatsapp-group-link-bef0d',
    storageBucket: 'whatsapp-group-link-bef0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvADkaO-VbFJ0JZkLoNCDfNMFIgLqpQu4',
    appId: '1:623939344647:ios:1be5d2cfe0c4b68dabcda2',
    messagingSenderId: '623939344647',
    projectId: 'whatsapp-group-link-bef0d',
    storageBucket: 'whatsapp-group-link-bef0d.appspot.com',
    iosClientId: '623939344647-q42qjkl9fqgjvm4nr78rabsttgsjgvmr.apps.googleusercontent.com',
    iosBundleId: 'com.zainon.whatsappGroupLinks',
  );
}
